In [69]:
import pandas as pd

In [84]:
data = pd.read_csv('fifa21 raw data v2.csv')

C:\Users\anmhm\AppData\Local\Temp\ipykernel_18020\1344703413.py:1: DtypeWarning: Columns (0: Hits) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('fifa21 raw data v2.csv')

In [71]:
data.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33.0,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35.0,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,NaN,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29.0,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28.0,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [72]:
data.tail()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21.0,47,55,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17.0,47,67,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18.0,47,65,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20.0,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21.0,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

In [73]:
data.describe()

,ID,Age,↓OVA,POT,BOV,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,...,GK Positioning,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY
count,18979.000000,18978.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,...,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000
mean,226403.384794,25.194014,65.718636,71.136414,66.751726,248.938142,49.688392,45.842405,51.942726,58.768112,...,16.217187,16.519627,1595.286949,355.702197,67.453975,53.457031,57.681016,62.875020,49.866221,64.368934
std,27141.054157,4.710626,6.968999,6.114635,6.747193,74.299428,18.131153,19.567081,17.294409,14.519106,...,17.002239,17.854079,269.874789,40.761117,10.677859,13.827425,10.081857,9.927415,16.443213,9.601883
min,41.000000,16.000000,47.000000,47.000000,48.000000,42.000000,6.000000,3.000000,5.000000,7.000000,...,2.000000,2.000000,747.000000,232.000000,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000
25%,210135.000000,21.000000,61.000000,67.000000,62.000000,222.000000,38.000000,30.000000,44.000000,54.000000,...,8.000000,8.000000,1452.000000,327.000000,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000
50%,232418.000000,25.000000,66.000000,71.000000,67.000000,263.000000,54.000000,49.000000,55.000000,62.000000,...,11.000000,11.000000,1627.000000,356.000000,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000
75%,246922.500000,29.000000,70.000000,75.000000,71.000000,297.000000,63.000000,62.000000,64.000000,68.000000,...,14.000000,14.000000,1781.000000,384.000000,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000
max,259216.000000,53.000000,93.000000,95.000000,93.000000,437.000000,94.000000,95.000000,93.000000,94.000000,...,91.000000,90.000000,2316.000000,498.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000

In [90]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  str
 2   LongName          18979 non-null  str
 3   photoUrl          18979 non-null  str
 4   playerUrl         18979 non-null  str
 5   Nationality       18979 non-null  str
 6   Age               18978 non-null  float64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  str
 10  Contract          18979 non-null  str
 11  Positions         18979 non-null  str
 12  Height            18979 non-null  str
 13  Weight            18979 non-null  str
 14  Preferred Foot    18979 non-null  str
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  str
 17  Joined            18979 non-null  str
 18  Loan Date End     1013 non-null   str
 19  Value             18979 non-null  str
 20  Wage              18979 non-null  str
 21  Release Clause    18979 non-null  str
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  str
 66  SM                18979 non-null  str
 67  A/W               18979 non-null  str
 68  D/W               18979 non-null  str
 69  IR                18979 non-null  str
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: float64(1), int64(53), object(1), str(22)
memory usage: 11.1+ MB

In [75]:
data.rename(columns={
"LongName" : "Full_Name",
"Preferred Foot" : "Preferred_Foot",
"Best Position" : "Best_Position",
"Loan Date End" : "Loan_Date_End",
}, inplace=True)

In [76]:
data.isna().sum()

ID              0
Name            0
Full_Name       0
photoUrl        0
playerUrl       0
             ...
PAS             0
DRI             0
DEF             0
PHY             0
Hits         2595
Length: 77, dtype: int64

In [77]:
data["Preferred_Foot"].value_counts()

Preferred_Foot
Right    14445
Left      4534
Name: count, dtype: int64

In [78]:
data["Preferred_Foot"].unique()

<StringArray>
['Left', 'Right']
Length: 2, dtype: str

In [79]:
data.dropna(subset=["Hits"], inplace=True)

In [80]:
data.isna().sum()

ID           0
Name         0
Full_Name    0
photoUrl     0
playerUrl    0
            ..
PAS          0
DRI          0
DEF          0
PHY          0
Hits         0
Length: 77, dtype: int64

In [91]:
mean = data['Age'].mean()

In [92]:
data['Age'] = data['Age'].fillna(mean)

In [ ]:
data.isna.count()

In [93]:
data.isna().info()

<class 'pandas.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  bool
 1   Name              18979 non-null  bool
 2   LongName          18979 non-null  bool
 3   photoUrl          18979 non-null  bool
 4   playerUrl         18979 non-null  bool
 5   Nationality       18979 non-null  bool
 6   Age               18979 non-null  bool
 7   ↓OVA              18979 non-null  bool
 8   POT               18979 non-null  bool
 9   Club              18979 non-null  bool
 10  Contract          18979 non-null  bool
 11  Positions         18979 non-null  bool
 12  Height            18979 non-null  bool
 13  Weight            18979 non-null  bool
 14  Preferred Foot    18979 non-null  bool
 15  BOV               18979 non-null  bool
 16  Best Position     18979 non-null  bool
 17  Joined            18979 non-null  bool
 18  Loan Date End     18979 non-null  bool
 19  Value             18979 non-null  bool
 20  Wage              18979 non-null  bool
 21  Release Clause    18979 non-null  bool
 22  Attacking         18979 non-null  bool
 23  Crossing          18979 non-null  bool
 24  Finishing         18979 non-null  bool
 25  Heading Accuracy  18979 non-null  bool
 26  Short Passing     18979 non-null  bool
 27  Volleys           18979 non-null  bool
 28  Skill             18979 non-null  bool
 29  Dribbling         18979 non-null  bool
 30  Curve             18979 non-null  bool
 31  FK Accuracy       18979 non-null  bool
 32  Long Passing      18979 non-null  bool
 33  Ball Control      18979 non-null  bool
 34  Movement          18979 non-null  bool
 35  Acceleration      18979 non-null  bool
 36  Sprint Speed      18979 non-null  bool
 37  Agility           18979 non-null  bool
 38  Reactions         18979 non-null  bool
 39  Balance           18979 non-null  bool
 40  Power             18979 non-null  bool
 41  Shot Power        18979 non-null  bool
 42  Jumping           18979 non-null  bool
 43  Stamina           18979 non-null  bool
 44  Strength          18979 non-null  bool
 45  Long Shots        18979 non-null  bool
 46  Mentality         18979 non-null  bool
 47  Aggression        18979 non-null  bool
 48  Interceptions     18979 non-null  bool
 49  Positioning       18979 non-null  bool
 50  Vision            18979 non-null  bool
 51  Penalties         18979 non-null  bool
 52  Composure         18979 non-null  bool
 53  Defending         18979 non-null  bool
 54  Marking           18979 non-null  bool
 55  Standing Tackle   18979 non-null  bool
 56  Sliding Tackle    18979 non-null  bool
 57  Goalkeeping       18979 non-null  bool
 58  GK Diving         18979 non-null  bool
 59  GK Handling       18979 non-null  bool
 60  GK Kicking        18979 non-null  bool
 61  GK Positioning    18979 non-null  bool
 62  GK Reflexes       18979 non-null  bool
 63  Total Stats       18979 non-null  bool
 64  Base Stats        18979 non-null  bool
 65  W/F               18979 non-null  bool
 66  SM                18979 non-null  bool
 67  A/W               18979 non-null  bool
 68  D/W               18979 non-null  bool
 69  IR                18979 non-null  bool
 70  PAC               18979 non-null  bool
 71  SHO               18979 non-null  bool
 72  PAS               18979 non-null  bool
 73  DRI               18979 non-null  bool
 74  DEF               18979 non-null  bool
 75  PHY               18979 non-null  bool
 76  Hits              18979 non-null  bool
dtypes: bool(77)
memory usage: 1.4 MB